# Dependencies
markdown:         redcarpet

# Setup
title:            RadNuclMagn
tagline:          by Antonino Rosaci
paginate:         5
baseurl:          '/'
url:              'http://rosaci.github.io'
permalink:        '/:year/:month/:title'
license:
  link:           'https://creativecommons.org/licenses/by-nc/3.0/'
  label:          'CC BY-NC'
author:
  name:           Antonino Rosaci
  url:            http://rosaci.github.io
  email:          arosaci@icloud.com

# Custom vars
version:          0.0.9
github:
  repo:           https://github.com/dottorblaster/dottorblaster.github.io
