# Dependencies
markdown:         redcarpet

# Setup
title:            MagNuclRad
tagline:          by Antonino Rosaci
paginate:         5
baseurl:          '/'
url:              'http://magnuclrad.com'
permalink:        '/:year/:month/:title'
license:
  link:           'https://creativecommons.org/licenses/by-nc/3.0/'
  label:          'CC BY-NC'
author:
  name:           Antonino Rosaci
  url:            http://magnuclrad.com
  email:          arosaci@icloud.com

# Custom vars
version:          0.0.9
github:
  repo:           https://github.com/dottorblaster/dottorblaster.github.io
